In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


## Hyperparameter Tuning


In [26]:
df = pd.read_csv(r"C:\Users\User\Desktop\study material\projects\datasets\ML ALGO PROJECTS\social.csv")
df.head(5)


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [27]:
x =  df[["Age","EstimatedSalary"]]
y = df["Purchased"]

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
sc = StandardScaler()
sc.fit(x,y)
x= pd.DataFrame(sc.transform(x), columns=x.columns)

In [14]:
from sklearn.model_selection import train_test_split

In [30]:
x_train , x_test , y_train , y_test =  train_test_split(x,y , test_size=0.2, random_state=42)

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [41]:
dt = DecisionTreeClassifier(criterion= "entropy",  max_depth=4, splitter="best")
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [42]:
dt.score(x_test,y_test)

0.9125

In [43]:
dt.score(x_train,y_train)

0.91875

In [35]:
from sklearn.model_selection import GridSearchCV , RandomizedSearchCV

In [38]:
df = { "criterion":["gini", "entropy", "log_loss"],
   "splitter":["best", "random"],
    "max_depth":[i for i in range(2,20)]}

In [39]:
gd = GridSearchCV(DecisionTreeClassifier(), param_grid=df )
gd.fit(x_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                       14, 15, 16, 17, 18, 19],
                         'splitter': ['best', 'random']})

In [40]:
gd.best_params_

{'criterion': 'entropy', 'max_depth': 4, 'splitter': 'best'}

In [44]:
gd.best_score_

0.903125

In [45]:
rd = RandomizedSearchCV(DecisionTreeClassifier(),param_distributions=df, n_iter=20)
rd.fit(x_train,y_train)

RandomizedSearchCV(estimator=DecisionTreeClassifier(), n_iter=20,
                   param_distributions={'criterion': ['gini', 'entropy',
                                                      'log_loss'],
                                        'max_depth': [2, 3, 4, 5, 6, 7, 8, 9,
                                                      10, 11, 12, 13, 14, 15,
                                                      16, 17, 18, 19],
                                        'splitter': ['best', 'random']})

In [46]:
rd.best_params_

{'splitter': 'best', 'max_depth': 6, 'criterion': 'log_loss'}

In [47]:
rd.best_score_

0.903125

##  Cross Validation 



In [49]:
dt = pd.read_csv(r"C:\Users\User\Desktop\study material\projects\datasets\ML ALGO PROJECTS\placment\placement.csv")
dt.head(2)

cgpa  package
0  6.89     3.26
1  5.12     1.98

In [50]:
x =  dt[["cgpa"]]
y = dt["package"]

In [51]:
new_data = dt.head(10)

In [54]:
x_new =  new_data[["cgpa"]]
y_new = new_data["package"]

#### LeaveOneOut , LeavePOut , KFold , StratifiedKFold Validation

In [52]:
from sklearn.model_selection import LeaveOneOut , LeavePOut , KFold , StratifiedKFold

In [55]:
lo = LeaveOneOut()

for train , test in lo.split(x_new,y_new):
    print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [58]:
lp = LeavePOut(p=2)

for train , test in lp.split(x_new,y_new):
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8

In [60]:
kf = KFold(n_splits=2)

for train , test in kf.split(x_new,y_new):
    print(train,test)

[5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4] [5 6 7 8 9]


In [63]:
from sklearn.linear_model import LinearRegression

In [64]:
from sklearn.model_selection import cross_val_score

In [66]:
p = cross_val_score(LinearRegression(),x,y,cv=5)

In [67]:
p.sort()
p

array([0.70887127, 0.75398043, 0.75683837, 0.78086775, 0.79051763])